[package]
name = "server_time_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsntp = '3.0.1'
chrono = '0.4.22'